### ISSUE TITLE
Escape nesting delimiters in identifiers [@redux-dynostore/core]

### ISSUE THREAD

**Issue by mpeyper** [ioof-holdings/redux-dynostore#2]
### Is it a bug, feature request or question?

Feature request

### Which package(s) does this involve?

@redux-dynostore/core

### Input Code & Current Behaviour

This issue is duplicating ioof-holdings/redux-dynamic-reducer#10 from the old library.

@anndroow says

> Hi,
> 
> In the documentation, there are three examples of using store.attachReducers():
> 
> ```
> store.attachReducers({
>     some: {
>         path: {
>             to: {
>                 dynamicReducer
>             }
>         }
>     }
> } )
> ```
> 
> `store.attachReducers({ 'some.path.to': { dynamicReducer } } } })`
> 
> `store.attachReducers({ 'some/path/to': { dynamicReducer } } } })`
> 
> The last two examples use a string to specify the path and in the last one, slash is used as the delimiter. But when using the first approach to describe the path of a nested location, it seems like slashes in the property names of the path object are treated as path delimiters as well. The thing is that we're using slashes in some of the property names in the state tree.
> 
> Here's an example of what's happening for us:
> 
> ```
> store.attachReducers({
>     routes: {
>         '/route1/section1': dynamicReducer
>     }
> } )
> ```
> 
> ...will end up like this:
> 
> ```
> {
>     routes: {
>         '': {
>             route1/section1': {...}
>         }
>     }
> }
> ```

### Possible Solution

It was proposed by @jpeyper that providing an escape function for the identifiers could resolve the issue:

```js
store.attachReducers({
    routes: {
        [escapeIdentifier('/route1/section1')]: dynamicReducer
    }
} )
```

**Comment by dantman** [comment]
I would love to be able to escape the identifier. I follow a `Company/Namespace/Slice/ACTION` pattern in naming my action types. I would like to be able to just use the same `Company/Namespace/Slice` as the identifier without it resulting in a deeply nested `Company.Namespace.Slice` tree in my redux state. It gets irritating inside dev tools because `Company` is at the start of every single slice in the product.

**Comment by dantman** [comment]
@mpeyper I don't actually know what code is responsible for the identifier. I tried looking at the code but I can't identify one spot I should change. Would you share what you've done so far as a base?

**Comment by mpeyper** [comment]
I've pushed up what I have done so far [here](https://github.com/mpeyper/redux-dynostore/commit/1c23f04915d28c9d9dbcd2e0741311936441177c).

I'm _think_ it's almost good to go, just needs some docs and maybe some tidying up.  The other bit I'm not sure on is how things like the saga handler will cope with an escaped identifier (it'll probably be fine as its a lot simpler than the reducer handler, but an test to prove it wouldn't go astray).

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
