### ISSUE TITLE
Support for react-redux v6

### ISSUE THREAD

**Issue by telesma** [ioof-holdings/redux-dynostore#20]
Do you plan to support react-redux v6 which provides compatibility for the new Context API?

https://github.com/reduxjs/react-redux/releases

**Comment by mpeyper** [comment]
Support is planned, but work has not started on it yet.

**Comment by jpeyper** [comment]
Might need to keep a few of the things mentioned here in mind...

https://github.com/reduxjs/react-redux/issues/1126

**Comment by Ethorsen** [comment]
Will keep an eye out for dynostore updates. Then we'll task a react-redux 6.x upgrade.

**Comment by VitaliyZadorozhnyy** [comment]
Any updates on this ?

**Comment by Ethorsen** [comment]
Hi guys,

Now that redux-subspace has been updated to use latest redux (thx to you), any chance you might tackle dynostore and bring it to the pace?

Thx

**Comment by mpeyper** [comment]
Hi @Ethorsen,

It's definitely on the to-do list and I'm planning on tackling it in the near future (just taking a small family-time break after the slog of the subspace upgrade).
