### ISSUE TITLE
is "immutable" reducer support in dynostore?

### ISSUE THREAD

**Issue by PitterL** [ioof-holdings/redux-dynostore#212]
Hi, Ioof:

Question:
How to attachReducer() if the reducer create from an  immutable expression?

import { fromJS } from 'immutable';

// The initial state of the App
const initialState = fromJS({
  loading: false,
  error: false,
  currentUser: false,
  username: "",
  userData: {
    repositories: false,
  },
});

function appReducer(state = initialState, action) {
    switch(action.type) {
        //...
        default:
            return state;
    }
}

// In home page
import rootReducer from './reducer';
....
export default dynamic(MODULE_NAME, subspaced(), attachReducer(rootReducer), runSaga(saga))(withConnect(HomePage));

// in subpage 1
import subReducer1 from './reducer';
....
export default dynamic(MODULE_NAME, subspaced(), attachReducer(subReducer1), runSaga(saga))(withConnect(SubPage1));

When you dynamic attached more page,  the state is not organized as the immutable map, just a normal member of the store, that will make data structure crash.

### Expected Behavior
Could support the immutable type store

Thanks.

**Comment by mpeyper** [comment]
We have an example of immutablejs support.  Does this help at all?

https://github.com/ioof-holdings/redux-dynostore/blob/master/examples/immutablejs/src/store.js#L9-L21

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
