### ISSUE TITLE
Immutable.js example stateHandler bug

### ISSUE THREAD

**Issue by karlshea** [ioof-holdings/redux-dynostore#218]
It looks like this line:

https://github.com/ioof-holdings/redux-dynostore/blob/a3b07cb9cf5e4a69a63e343f14e369e246e74a77/examples/immutablejs/src/store.js#L11

should use `keySeq()` instead. There's no `forEach()` method on the ES6 iterator that Immutable.js returns. Took me quite a while to track down why my lazy-loaded components couldn't add a reducer.

It's called from `filteredReducer()` here: https://github.com/ioof-holdings/redux-dynostore/blob/1273eae27f638a15047ec03d4c7d01735b5192fc/packages/redux-dynostore-core/src/reducers/filteredReducer.js#L43

**Comment by karlshea** [comment]
Also when you're creating an initial store, it also appears that you can't use redux-immutable's `combineReducers()`. You have to use the one from redux-dynostore and pass in `combineReducers(rootReducer, { stateHandler: immutableJsStateHandler }`

**Comment by mpeyper** [comment]
This was definitely working when I wrote it.  It's entirely likely that something has been broken along the way though.

The bit about `combineReducers` is interesting.  The example doesn't have a combined root reducer so I didn't stumble across that one.  If this is insurmountable, we should add a note somewhere in that example or one of the READMEs to let people know.

I'll leave this open until either the code can be fixed to support ImmutableJS better or docs have been updated to better highlight the constraints.

Happy to review PRs from anyone better acquainted with ImmutableJS then me.

**Comment by karlshea** [comment]
It doesn't actually break in the example since the example doesn't set up an initial set of reducers or state, so that function doesn't seem to ever be called where it would fail. I should have some time to get a PR for the immutable example in the next day or so.
