### ISSUE TITLE
Support for redux-saga v1

### ISSUE THREAD

**Issue by qn895** [ioof-holdings/redux-dynostore#22]
### Is it a bug, feature request or question?

Feature request

### Which package(s) does this involve?

redux-subspace-saga
redux-dynostore-redux-saga
redux-dynostore-redux-subspace-saga

### Input Code

Please see the following sandbox and look for the test results. This is a fork from github with minimal change except for the package upgrade.

https://codesandbox.io/s/j49y25o659

### Expected Behavior

Sagas should be running

### Current Behavior

Sagas is not running

### Possible Solution

Upgrade peer dependency or dependency of the saga-related packages.

### Context

I have come across a minor issue with an internal package from my company exporting sagas that are generated from version 1.0.0. The new version introduced some breaking changes, one of which is the refactor of the shape of the effect objects from `{[IO]: true, [type]: payload }` to `{ [IO]: true, type, payload }`. While the shape shouldn't really matter, upgrading redux-saga to v1 while using createSagaMiddleWare from redux-subspace saga won't make the dynamicSagas "listen" to the effects correctly. That is, they are completely ignored. 

After looking through some pull requests related to version 1, I think it might also be the fact that v1 no longer uses emit.

I do understand the current dependency works great as is so I don't expect urgency on supporting the new version. However, I would like some pointers on how to potentially upgrade the dependency on my own.

**Comment by jpeyper** [comment]
Sorry an identical button press :(

**Comment by jpeyper** [comment]
We definately have plans to support v1 now that it's out. Subspace is really where the bulk of the changes will be, and depending on the breaking changes (which we're yet to go over) it might be easy or very hard to do the upgrade.

PRs are most definately welcome at this stage and we will help where we can.
