### ISSUE TITLE
If the state of reducer is an object, new state is a merge of previous and returned value

### ISSUE THREAD

**Issue by mihhauk** [ioof-holdings/redux-dynostore#23]
### Bug

If the state of reducer is an object, new state is a merge of current state and returned value

### Which package(s) does this involve?

@redux-dynostore (not sure which package) version: 2.0.0

```
const sampleReducer = (state = {}, action) => {
  switch (action.type) {
    case 'SET_VALUE':
      return { ...action.value }
    case 'RESET_VALUE':
      return { }
  }
  return state
}

const state = { foo: 'bar' }

const newState = sampleReducer(state), {type: 'SET_VALUE' }, value: { new: 'val' })
const resetState = sampleReducer(state), {type: 'RESET_VALUE' })

```

### Expected Behavior

newState is equal to { new: 'val' }
resetState is equal to { }

### Current Behavior

newState is equal to {  foo: 'bar', new: 'val' }
resetState is equal to { foo: 'bar' }

### Context

Confirmed with unit tests that single reducer has expected behaviour, bug happens only when combining reducers using redux-dynostore

### Your Setup

| package         | version(s)
| --------------- | ----------
| redux           | 4.0.0
| redux-dynostore | 2.0.0

**Comment by mpeyper** [comment]
Also, I suspect that the issue is a bit more serious than just resetting the state, as I think it may make it impossible to actually remove any keys at all.
