### ISSUE TITLE
Dispatch an action to subspaced reducers of an already instantiated dynamic

### ISSUE THREAD

**Issue by Ethorsen** [ioof-holdings/redux-dynostore#24]
Hi guys,

Would it be possible to dispatch actions to a subspace but, as opposed to the dispatchAction enhancer, at any time **after** it has been instantiated?

Thx

**Comment by jpeyper** [comment]
Hi, and thanks for your question.

I believe this is already possible and the intended , can you post the snippet of your `dynamic` and imports so we can better understand the what you're trying to achieve and where it might be going wrong?

**Comment by jpeyper** [comment]
I've just been chatting with @mpeyper, and perhaps I'm wrong...

In any case, getting a but more information about your you're setting up your target and expected outcomes will help us make sure we're answering the right question.

**Comment by Ethorsen** [comment]
I have a particular dynamic module, that will be instantiated once and shown in a dialog when a user is requesting to open it.  When the dialog is being opened, I want to inject some values in the module store (ex. return path, callback function, etc)   



Module is declared and exported like
`DialogModule = dynamic('dialogModule', attachReducer(ModuleOwnReducers))(DialogModule );`

Then is created with
```
const newModuleInstance = DialogModule.createInstance(
        moduleId,
        subspaced({ mapExtraState:
            (_state) => ({
              moduleInfo: _state.app.openedModules.get(moduleId),
              userPreference: _state.auth.userPreference,
            })
        })
      );

```
This instance is then stored in a cache to be re-used whenever we want to show the dialog (the state need to persist)

I know I could:
1- Pass down props to it when I push it in the DOM.   But this is problematic as the handler pushing it in the DOM is react-router based and doesn't know the values I want to pass down.

2- Create a new mapExtraState entry.  But I think this would be less than ideal, as it would required handling a new reducer at root level only to push specific working data that only concern the DialogModule.

Ideally, I'd like to be able to dispatch an action to ${newModuleInstance} at any time while its not yet in the DOM, and then move the user to it. 

ex. Thunk action I'd like to come up with

```
import { push } from "react-router-redux";
import { dispatchAction } from '@redux-dynostore/redux-subspace'; 
export const openDialogModule = (moduleRouteToOpen, returnRoute = null, callback = null) => {
  return function (dispatch, getState) {

      const moduleInstance = getModuleInstanceFromCache();
      dispatchAction(moduleInstance, { TYPE: INITIALIZE, returnRoute: returnRoute, callback: callback });
      dispatch(push("/moduleBaseRoute" + moduleRouteToOpen));
  }
};
```

I hope this all makes sense

**Comment by jpeyper** [comment]
So if I'm understanding correctly,

You actually want to fire an action from outside the subspace that will be handled within the subspace.

We've usually used props for this case, but we've had context of what we wanted to pass in (ie, not a reusable dialog).

Subspace has a feature to [scope actions](https://ioof-holdings.github.io/redux-subspace/docs/advanced/ScopingActions.html).

At the very least you could use the global action and a unique action type to do what you want, but I'd you know the namespace you could target your dialogs subspace only.

I also should mention that I think there are rules about actions and state being serialisable, and not sure passing a callback function to store in state is a good idea.... But I'm far from a redux expert.

**Comment by Ethorsen** [comment]
Yes scope actions is exactly what I needed.

And I believe you are right about the state, pushing functions in it is probably not a good idea. I know it is working for having done some tests with this, but I'm sure it's a real bad practice.  I'll explore some other possibilities.

Thx a lot for you help.

**Comment by jpeyper** [comment]
Cool I'll close this issue now, but please feel free to open again if you need any more help or advice.
