### ISSUE TITLE
type declaration is necessary for typescript user

### ISSUE THREAD

**Issue by chuyuandu** [ioof-holdings/redux-dynostore#263]
feature request

there's no declaration file in the package
it will raise an eslint error in default  CRA project
type declaration is necessary for users

**Comment by mpeyper** [comment]
This package does a lot of crazy dynamic things that are difficult to statically type (or at least beyond my Typescript abilities).

If anyone want to take this on, I'd gladly accept a PR to add type definitions.

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
