### ISSUE TITLE
Intermittent undefined state when a reducer is re-attached.

### ISSUE THREAD

**Issue by n-mcnally** [ioof-holdings/redux-dynostore#425]
### Is it a bug, feature request or question?

Bug

### Which package(s) does this involve? 

 [@redux-dynostore/core, @redux-dynostore/react-redux]

### Input Code

This implementation uses a simple `withReducer` HOC to attach and detach the provided reducers with the component.

[Code Sandbox](https://codesandbox.io/s/redux-dynostore-detach-crash-45c30)

### Expected Behaviour

When a component using `withReducer` is mounted the reducers should be attached then detached once unmounted.

### Current Behaviour

A small percentage of the time when re-attaching the reducer the state becomes `undefined` and causes the selectors to throw an error.

> Cannot read property 'value' of undefined

*After further investigation this issue only occurs whilst the Redux Devtools plugin is enabled.*

### Context

Parts of our app (data tables, grids) require large state trees and are rarely used more than once so would benefit from a reusable HOC for detaching the reducer once the component unmounts.

### Your Setup

| Package Name                 | Version |
|------------------------------|---------|
| React                        | 17.0.1  |
| @redux-dynostore/core        | ^3.1.0  |
| @redux-dynostore/react-redux | ^3.1.0  |
| redux-dev-tools         | 2.17.0 |

**Comment by n-mcnally** [comment]
After further investigation this issue only seems to only occur whilst the Redux Devtools plugin is enabled.

**Comment by mpeyper** [comment]
Hi @n-mcnally,

Can you please confirm if this is still an issue?  The sandbox appears to be working as I'd expect.

**Comment by n-mcnally** [comment]
Hi @mpeyper,

Thanks for having a look! I've just gave it another go and can confirm the problem is still occurring.

It typically works as expected the first time the reducer is mounted/unmounted but then when it's remounted i get the undefined state in the selectors.

I have also confirmed in our app as well this problem only occurs when the redux devtools are enabled, if that's any use.

**Comment by mpeyper** [comment]
Closing. Please see #484 for details.
