### ISSUE TITLE
[Question] Adding reducer dynamically without component

### ISSUE THREAD

**Issue by damon3465** [ioof-holdings/redux-dynostore#469]
I want to separate ui and dynamic attachreducer

My goal is when customer adding module in him self package. This modules has ui and many reducers.He can be add ui component then he choosing a reducer.

I don't know very well about redux but my goal is this kind of scenario.

**Comment by mpeyper** [comment]
The core package can attach reducers without an component (i.e. just redux).

[Here are the docs](https://github.com/ioof-holdings/redux-dynostore/tree/master/packages/redux-dynostore-core#manually-attaching-reducers).  Let me know if that doesn't solve your issue.

**Comment by damon3465** [comment]
Yes solved but I have two components that I want to access two different registered states The action I call in todo1 component affects the component's state as todo2.

**Comment by damon3465** [comment]
https://github.com/ioof-holdings/redux-subspace This solved my problem thanks
