### ISSUE TITLE
Attached reducers are not immediately available when using redux v4 and redux-devtools-extension

### ISSUE THREAD

**Issue by telesma** [ioof-holdings/redux-dynostore#7]
Question:
I am struggling with dynamically attached reducers and async loaded components via 'react-loadable'. Looks like the store gets only updated after navigating a 2nd time to the async component. Meaning the component is already loaded. 

Is there any use case for this kind of scenario? Would be really nice to load the reducers at the same time as the async component.

**Comment by mpeyper** [comment]
Hi @telesma,

Mounting the component with react-loadable should _just work_. In fact this was the primary use case for us for a long time (we replaced react-loadable with a custom solution, but the concept is still the same).

Can you set up a simple [codesandbox](https://codesandbox.io) to show the problem. I might have time later this morning to create a working example for you too.

**Comment by telesma** [comment]
Hi @mpeyper,

yes, I am using redux v4 and the redux-devtools and I can confirm switching back to redux v3 does resolve the issue.

Thank you for your effort digging into this issue!

**Comment by mpeyper** [comment]
No worries.  I'll leave this open until it's confirmed to be fixed so others might find it.

**Comment by mpeyper** [comment]
I have confirmed that the redux-devtools and redux-devtool-extension issue has been resolved and this bug is no longer occurring in the above code sandboxes.

Closing.
